/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.0 		*/
/*  Created On : 03-May-2022 19:21:22 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

 

 
create database if not 
 

/* Drop Tables */

DROP TABLE IF EXISTS applicant_login CASCADE
;

DROP TABLE IF EXISTS applicant_skills CASCADE
;

DROP TABLE IF EXISTS skillslist CASCADE
;

/* Create Tables */

CREATE TABLE applicant_login
(
	id bigserial NOT NULL,
	username varchar(256) NOT NULL,
	password varchar(1000) NULL,
	firstname varchar(256) NULL,
	lastname varchar(256) NULL
)
;

CREATE TABLE applicant_skills
(
	id bigserial NOT NULL,
	applicant_login_id bigint NOT NULL,
	skillid bigint NOT NULL
)
;

CREATE TABLE skillslist
(
	id bigserial NOT NULL,
	name varchar(256) NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE applicant_login ADD CONSTRAINT pk_student_user_login
	PRIMARY KEY (id)
;

ALTER TABLE applicant_skills ADD CONSTRAINT pk_applicant_skills
	PRIMARY KEY (id)
;

CREATE INDEX "IXFK_applicant_skills_applicant_login" ON applicant_skills (applicant_login_id ASC)
;

CREATE INDEX "IXFK_applicant_skills_skillslist" ON applicant_skills (skillid ASC)
;

ALTER TABLE skillslist ADD CONSTRAINT pk_skillslist
	PRIMARY KEY (id)
;

/* Create Foreign Key Constraints */

ALTER TABLE applicant_skills ADD CONSTRAINT "FK_applicant_skills_applicant_login"
	FOREIGN KEY (applicant_login_id) REFERENCES applicant_login (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE applicant_skills ADD CONSTRAINT "FK_applicant_skills_skillslist"
	FOREIGN KEY (skillid) REFERENCES skillslist (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

 

 

 
